// Terms.jsx — Terms of Service (/terms)
// Governing law: England and Wales (UK)
// Required before any user accounts are created

import { Link } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import TopNav from '../components/TopNav'
import PageMeta from '../components/PageMeta'

const LAST_UPDATED = '19 June 2026'
const CONTACT_EMAIL = 'hello@chatterclub.app'
const BRAND = 'Chatter Club'
const SITE = 'chatterclub.app'

export default function Terms() {
  const { userId, isPro, checking } = useAuth()

  return (
    <div className="min-h-screen bg-white flex flex-col">
      <PageMeta
        title="Terms of Service"
        description="Terms and conditions for using Chatter Club."
        canonical="/terms"
      />

      <TopNav userId={userId} isPro={isPro} checking={checking} />

      <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <div className="mb-10">
          <p className="text-xs text-gray-400 mb-2">Last updated: {LAST_UPDATED}</p>
          <h1 className="text-3xl font-bold text-gray-950 mb-3">Terms of Service</h1>
          <p className="text-gray-500 leading-relaxed">
            By using {SITE} (the "Service"), you agree to these terms. Please read them carefully.
          </p>
        </div>

        <div className="space-y-8">

          <Section title="1. About the Service">
            <p>
              {BRAND} is an English learning platform operated by Joe Allport, based in the United Kingdom.
              The Service provides learning content including articles, courses, challenges, puzzles and vocabulary tools.
            </p>
          </Section>

          <Section title="2. Eligibility">
            <p>
              You must be at least 16 years old to create an account. By creating an account,
              you confirm that you are 16 or older. If you are under 18, you confirm that a parent
              or guardian has agreed to these terms on your behalf.
            </p>
          </Section>

          <Section title="3. Your account">
            <ul>
              <li>You are responsible for keeping your account credentials secure.</li>
              <li>You may not share your account or use another person's account.</li>
              <li>You must provide accurate information when creating your account.</li>
              <li>We may suspend or terminate accounts that violate these terms.</li>
            </ul>
          </Section>

          <Section title="4. Free and Pro access">
            <p>
              Some content is available to all users for free. Pro features require a paid subscription.
              We reserve the right to change what is free and what is paid at any time, with reasonable notice.
            </p>
            <p>
              Subscriptions are billed monthly or annually. You can cancel at any time.
              No refunds are provided for unused portions of a subscription period, except where required by law.
            </p>
          </Section>

          <Section title="5. Acceptable use">
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to gain unauthorised access to any part of the Service.</li>
              <li>Copy, resell or redistribute any content from the Service without permission.</li>
              <li>Use automated tools (bots, scrapers) to access the Service.</li>
              <li>Submit content that is offensive, harmful, or infringes third-party rights.</li>
            </ul>
          </Section>

          <Section title="6. Content and intellectual property">
            <p>
              All content on {BRAND} — including articles, exercises, course materials, explanations
              and audio — is owned by or licensed to us. You may use it for your personal learning only.
              You may not reproduce, distribute or create derivative works without our written permission.
            </p>
            <p>
              Content generated by AI tools (including writing feedback) is provided as a guide only.
              It may contain errors and should not be relied upon as professional advice.
            </p>
          </Section>

          <Section title="7. AI features">
            <p>
              Some features use AI (including Anthropic's Claude). AI-generated content may occasionally
              be inaccurate. We do not guarantee the accuracy of AI feedback, scores or recommendations.
              Use your own judgment.
            </p>
          </Section>

          <Section title="8. Disclaimers and limitation of liability">
            <p>
              The Service is provided "as is" without warranties of any kind. We do not guarantee
              uninterrupted access, error-free operation, or that the Service will meet your specific
              requirements.
            </p>
            <p>
              To the maximum extent permitted by law, we are not liable for indirect, incidental,
              or consequential damages arising from your use of the Service.
            </p>
            <p>
              Nothing in these terms limits our liability for death or personal injury caused by
              our negligence, or for fraud or fraudulent misrepresentation.
            </p>
          </Section>

          <Section title="9. Changes to the Service">
            <p>
              We may change, suspend or discontinue any part of the Service at any time.
              We will give reasonable notice of significant changes that affect paid users.
            </p>
          </Section>

          <Section title="10. Changes to these terms">
            <p>
              We may update these terms from time to time. We will notify you by email if we make
              significant changes. Your continued use of the Service after changes are posted
              constitutes acceptance of the new terms.
            </p>
          </Section>

          <Section title="11. Governing law">
            <p>
              These terms are governed by the laws of England and Wales. Any disputes will be
              subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>
          </Section>

          <Section title="12. Contact">
            <p>
              Questions about these terms: <a
                href={`mailto:${CONTACT_EMAIL}`}
                className="text-gray-900 underline"
              >
                {CONTACT_EMAIL}
              </a>
            </p>
          </Section>
        </div>

        <div className="mt-12 pt-6 border-t border-gray-100 flex items-center gap-4 text-sm text-gray-400">
          <Link to="/privacy" className="hover:text-gray-700 transition-colors">Privacy Policy</Link>
          <Link to="/" className="hover:text-gray-700 transition-colors">Back to home</Link>
        </div>
      </main>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <section>
      <h2 className="text-base font-bold text-gray-900 mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-gray-600 leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5">
        {children}
      </div>
    </section>
  )
}
